#!/usr/bin/env python3
"""Debug script to trace the exact error in get_k8s_client_from_content"""
import sys
import traceback
import tempfile
import os
sys.path.insert(0, '/app/backend')
from kubernetes import client, config

# Simulate the kubeconfig with docker-desktop context (inline cert data)
# Using a minimal kubeconfig that mirrors the actual one
KUBECONFIG = """apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://kubernetes.default.svc.cluster.local:443
  name: docker-desktop
- cluster:
    certificate-authority: /nonexistent/path/ca.crt
    server: https://127.0.0.1:63624
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: docker-desktop
kind: Config
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWlxZ0F3SUJBZ0lJWFppNGwrdTY5OU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1qVXlNVFUzTXpaYUZ3MHlOekF4TWpVeU1UVTNNelphTURZeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sc3dHUVlEVlFRREV4SmtiMk5yWlhJdFptOXlMV1JsCmMydDBiM0F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE5VTk9idmNFNm4wODIKYllZaHZ2Zjk1TjNQRGs1VFJNb1BhR2x2dWJ0V20weEo5UUgzb1haeGxDQWdSUjBFTHZTaEduV0NWZDZzbTBJMwprekM5ckJRVnNVY2g0SndKVTV2YUkrQjdKd1lrZkp6SXBLK2F2MXhhdlFaWFYxc1FOZGxUb2ErcFlHTmJQUVU1CnJPT0YvMTBHWXBsbXJGNSt5R0xocnBud1dMalFscEl4YkFKTWNOWVFmQ1R5QndPZE1DbFJGUlU4RUMwV3BFSEsKZGhGb2EzL21ISkhPYnZxU25nZkxjNEszSE9qQi92V0ZkNzYyMU5ud2hkMUk0c2VuVlViemI0SWlBa3BxUTBCUwpkRWh5OUtVYzZHcGg5MmhDY0Z2ZEdhcGFuQlpXTngyNjdYQitvd080REViZy95enBia2xOMG1rRFdFR1dHa0dpClFjZlVYZ01kQWdNQkFBR2pkVEJ6TUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZOSzNQbDZRT2JGMXFhM0xnYkp1Z2JQcgp5dDdDTUIwR0ExVWRFUVFXTUJTQ0VtUnZZMnRsY2kxbWIzSXRaR1Z6YTNSdmNEQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBUDFyTGx4RFBEejM1RGxQOWEzYlkvNCtNQmVhN0I3RFNGeDRjaHEyeXNPelNUWGFmeEl1clhlSFQKd2M2U3gyUjhjTmJWajZmZEhzRFRLQU43S2tybkFUQ25iVnY0TGJYY2NYRG5kWDI2T2d4NmFzR0tVSTlML3drNwp0RnRBY2tvSDdMNzJEOUxnMnJGSHhpNEJwd3FmMjZzaDJJSVBwaXgxT0xVd3hBNUovSk5DQitsZ1IwUWxUS0IwClB4a3I3UXh3NGs4RlhnOE9yQVM2d3krOWl5MTIxajdURFF3RE4waTUrK0VZMFF0a0tCQlVrT1RTbDdXbjJIakkKSm1JUzJZMnpzcEVjTW55RlZQTDlENmlwcVVIWlhjU0I1NWlQbmNrNkl3R2JGNDFLdjVJem1OL0xJQ1hCUm9FUwpsZ2podThEdnQ3MS8velVpS0JLSnU0NEJBdUkwSWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBelZEVG03M0JPcDlQTm0yR0liNzMvZVRkenc1T1UwVEtEMmhwYjdtN1ZwdE1TZlVCCjk2RjJjWlFnSUVVZEJDNzBvUnAxZ2xYZXJKdENONU13dmF3VUZiRkhJZUNjQ1ZPYjJpUGdleWNHSkh5Y3lLU3YKbXI5Y1dyMEdWMWRiRURYWlU2R3ZxV0JqV3owRk9hempoZjlkQm1LWlpxeGVmc2hpNGE2WjhGaTQwSmFTTVd3QwpUSERXRUh3azhnY0RuVEFwVVJVVlBCQXRGcVJCeW5ZUmFHdC81aHlSem03NmtwNEh5M09DdHh6b3dmNzFoWGUrCnR0VFo4SVhkU09MSHAxVkc4MitDSWdKS2FrTkFVblJJY3ZTbEhPaHFZZmRvUW5CYjNSbXFXcHdXVmpjZHV1MXcKZnFNRHVBeEc0UDhzNlc1SlRkSnBBMWhCbGhwQm9rSEgxRjRESFFJREFRQUJBb0lCQURGSlRSYm1tUTlkeFZucgpOa2I5RFJLUGdYaU9ObHF5V1hBVDhEV1FDQ3JzNmtZWnNPQjFTOVhOaVYyOXdZNnF4L0l4aEJKbTB5YXJ1WnhXCk10M2hSRXdGeTYzVCtaa2Fqei94RzFiczRnSlp3SmhBd2wvYlBvd1Fzc2crTWQvRkVYZk1TVHNYWnBwMUhqOC8KWTduYnVJVExJQWgvNmNvMUI5bWx2Skh2OW1PcHgzRFpxN2xOYnVFVk1qMlA2OUgwNDhvazA1aTY0ZitXQlVuTQpmR0lXU2ljajUrVHkrMjJpRTB4eVdCZ0JxZ3A0MGYzaUZBODR4dU1JT1Juai9aaWk3aHhTbUVyRlZDV3hGRU54CjkxanoyTDVyVTFJemxRblltZTlCODdrYkdZSVJYeHA1T3p5NDZaM0NlRVJSK3VlZzdYdkhoQXFjb0FKQVU0SWwKYXd6SXRjRUNnWUVBMzVEajBhWkR4NHdHWEhCamJFeFRNeHlDcmpYNG1EZk42c3NpZTJRVldLd0Foa3JFY2crNApwcjVjMDlSbGF5N0NYcHlIdTBBTUhYNG1jVWFRd1NIbW5lWmlMME9vSGJ4cVlmQmdESTFJbWFwWkFucHRLKy9lCjQydm4vZ2ZrSUY3dG9QZXFJdVZ1K1I2Z1VjcEc0anNqSmkwdVpxR1gveGF5TDBsblhtSTFCOTBDZ1lFQTZ4b2kKRklHdzRUa2piNTl6aW5aMkFMcWE0RnQ2TVNxZCtYL240NHVQaDVCekQ0SHBKcTBmWWdMR0VjbDhoZUpPV3ZuSApPMlFmV1FlMzJ3eW42VEpLNU5UUjJzMHN3NUJRTTg3cXJINmxGTDh5a3BEaEd3S2R0ZmhWVklSTm5wS2tCeHF5CldxZFdZT3ZNZ2pqTllwWlBrK1k4UEU4bUtMZGFlTkJ5bTQrMDFFRUNnWUFRTGdVKzNBQ1Z4WDJFWFNIazZaVXYKNHNWV1pGT01lS1Z2YzZvWU1nTVZlc1ZDOHRCS3pQWjVJdGZIQU4waUo2MHJlYnFkQTZLYzA4OW1iVXYybmtSNQpjdjN5Rzd4a0FvblVjcmdRMEh6TG1qZDg1VzFYTzdIdTFaVmhuaUtWY1NsVGQva1pNMitYbWU3U1hJaEt3U3JuCkRXZ0pSM0tmcEgzYXpENHQ1MytkQlFLQmdRREd1REVrU2pjYk9EUEdydTEzbFFmTE4rK2ZRbE0zYWNGYjJneEUKbm50MFo5bUp1eEk2dWN5MENJb3BFTGpyWmMwN1FyTnZkUUsyT3pyaHNZSGdMNzEwVEpzUkthbnpwM0RUU2N1OApmOVBEaEpVWG85UlNBMVVSTWRYV2VYb3VWZDdGam9CQTlmNmlMODJPS0xzWjRObGt0eEFsSGZXd0pzTVhLWUltCkVVTVV3UUtCZ1FEU0dqeHp3Q01vRWJBclk5N1p6OXRrdHZhamllK1crYVd2L2dKa3BuQkVVa2VDNi90SDlKMGkKaUFFV21wV29VV2lZbTk5WUp1Vk8wbjFtK0FiNkpydTh1V050MXdmc29FOFdJb0tWREc0ZlZia2pYQXhzb1R6dgpvL0c3VnVvK1hMRE5zSURIYUNTa1UzUGVLeVhFaTdvMmRCQWJUcnJtbVdIeVkzbm1hekFTdEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
- name: minikube
  user:
    client-certificate: /nonexistent/minikube/client.crt
    client-key: /nonexistent/minikube/client.key
"""

print("Testing kubeconfig loading with docker-desktop context...")
try:
    tf = tempfile.NamedTemporaryFile(mode='w', suffix='.kubeconfig', delete=False)
    tf.write(KUBECONFIG)
    tf.close()
    print(f"Temp file: {tf.name}")
    
    config.load_kube_config(config_file=tf.name, context='docker-desktop')
    v1 = client.CoreV1Api()
    print("SUCCESS: Kubernetes client created")
    
except Exception as e:
    print(f"ERROR: {type(e).__name__}: {e}")
    traceback.print_exc()
finally:
    try:
        os.unlink(tf.name)
    except:
        pass

print("Done.")
