apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-chatbot
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/apps/devops-chatbot
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: bookish-octo-robot