apiVersion: v1
kind: Service
metadata:
  name: devops-chatbot
  namespace: devops-chatbot
  labels:
    app: devops-chatbot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: devops-chatbot
