apiVersion: v1
kind: Secret
metadata:
  name: k8sgpt-ai-secret
  namespace: k8sgpt-operator-system
type: Opaque
stringData:
  openai-api-key: "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"
