apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-openrouter
  namespace: k8sgpt-operator-system
spec:
  version: v0.4.27
  ai:
    enabled: true
    backend: openai
    model: openrouter/auto
    baseUrl: https://openrouter.ai/api/v1
    secret:
      name: openrouter-secret
      key: openai-api-key
    # This enables the masking of sensitive cluster data
    anonymized: true
  analysis:
    interval: 5m