apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bookish-octo-robot
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/pandew-home/bookish-octo-robot