apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bookish-octo-robot
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: improve-api-docs-error-handling
  secretRef:
    name: flux-system
  url: https://github.com/pandew-home/bookish-octo-robot