apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-chatbot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devops-chatbot.labels" . | nindent 4 }}
