apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bookish-octo-robot
  sources:
    - repoURL: https://github.com/pandew-home/bookish-octo-robot.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.k8sgpt.ai/
      chart: k8sgpt-operator
      targetRevision: 0.2.27
      helm:
        valueFiles:
          - $values/k8sgpt/helm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
