apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-chatbot
  namespace: devops-chatbot
  labels:
    app: devops-chatbot
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: localhost
    http:
      paths:
      - path: /chatbot
        pathType: Prefix
        backend:
          service:
            name: devops-chatbot
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: devops-chatbot
            port:
              number: 80
