apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-chatbot-pvc
  namespace: devops-chatbot
  labels:
    app: devops-chatbot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
